/*
 * Generated by inst.cpp 
 * This file is used to retrieve files hyaccpar and hyaccmanpage.
 * This file is updated each time hyacc is installed.
 */

#include "y.hpp"

void show_manpage()
{
  system("less /usr/local/lib/hyacc/hyaccmanpage");
}

const char * HYACC_PATH = 
"/usr/local/lib/hyacc/hyaccpar";

